#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts._new
echo "127.0.0.2		localhost" > ~/hosts._new
echo "8.8.8.8		facebook.com" >> ~/hosts._new
cp -f ~/hosts._new /etc/hosts
