#!/usr/bin/env bash
# Fixes a container so that Nginx is running as the nginx user.
#	- nginx must be running as nginx user
#	- nginx must be listening on all active IPs on port 8080

# Set a user in the config by replace '#user' and by nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# Replace port 80 with 8080 in the sites-available config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# Give owner permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf
# Apache may interfere with nginx so kill the process if it is running
pkill apache2
# Start the nginx service with the new nginx user
sudo -u nginx service nginx start
